#%RAML 1.0 NamedExample
value:
  - id : "1"
    firstName: "Ramesh"
    lastName: "Thombre"
    address : "Mumbai-Banglore highway, Baner"
    postalcode : "411045"
    country: "India"
    date : "2019-01-04"

  - id : "2"
    firstName: "John"
    lastName: "Doe"
    address : "Wall street, Dallas"
    postalcode : "65487"
    country: "US"
    date : "2019-01-25"